### ISSUE TITLE
Error processing block headers

### ISSUE THREAD

**Issue by lawlawlaw** [commerceblock/cb-electrum-wallet#11]
Error in processing Ocean block headers.

The code tries to process a field called 'bits' from the blockchain header. This field is not returned by the electrum server deserializer.

Traceback (most recent call last):
  File "/Users/lawrence/Projects/cb-electrum-wallet/electrum/util.py", line 882, in run_with_except_hook
    run_original(*args2, **kwargs2)
  File "/Users/lawrence/Projects/cb-electrum-wallet/electrum/network.py", line 1089, in run
    self.wait_on_sockets()
  File "/Users/lawrence/Projects/cb-electrum-wallet/electrum/network.py", line 1065, in wait_on_sockets
    self.process_responses(interface)
  File "/Users/lawrence/Projects/cb-electrum-wallet/electrum/network.py", line 719, in process_responses
    self.process_response(interface, response, callbacks)
  File "/Users/lawrence/Projects/cb-electrum-wallet/electrum/network.py", line 659, in process_response
    self.on_get_header(interface, response)
  File "/Users/lawrence/Projects/cb-electrum-wallet/electrum/network.py", line 913, in on_get_header
    can_connect = blockchain.can_connect(header)
  File "/Users/lawrence/Projects/cb-electrum-wallet/electrum/blockchain.py", line 149, in can_connect
    if b.can_connect(header):
  File "/Users/lawrence/Projects/cb-electrum-wallet/electrum/blockchain.py", line 487, in can_connect
    target = self.get_target(height // 2016 - 1)
  File "/Users/lawrence/Projects/cb-electrum-wallet/electrum/blockchain.py", line 442, in get_target
    target = self.bits_to_target(bits)
  File "/Users/lawrence/Projects/cb-electrum-wallet/electrum/blockchain.py", line 452, in bits_to_target
    bitsN = (bits >> 24) & 0xff
TypeError: unsupported operand type(s) for >>: 'NoneType' and 'int'

The field 'bits' is in the Ocean blockchain header, according to blockchain explorer.

**Comment by nkostoulas** [comment]
This probably happens when the wallet hasn't updated for some time and it updates block headers in batches. 

I never encountered this but probably happened with you because you get block headers from testnet and you hadn't updated since yesterday. 

Since there's no bits in Ocean we can probably just set target to 0 or some other arbitrary value.
